# Generated by Django 3.1.3 on 2021-06-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_question_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mainphoto',
        ),
    ]
