# Generated by Django 3.1.3 on 2021-06-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
