# Generated by Django 3.1.3 on 2021-06-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='post',
            new_name='question',
        ),
    ]
