# Generated by Django 3.1.3 on 2021-06-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20210616_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
