# Generated by Django 3.1.3 on 2021-06-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
