# Generated by Django 3.1.3 on 2021-06-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20210616_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
    ]
